# Generated by Django 4.1.7 on 2023-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
